CREATE OR REPLACE PACKAGE RDM.SQA_QC
IS
TYPE GenRefCursor IS REF CURSOR;
TYPE JOB_TITLES IS RECORD 
(
JOB_TITLE  DBMS_SQL.VARCHAR2_TABLE,
JOB_NAMES  DBMS_SQL.VARCHAR2_TABLE,
ACTIVE     DBMS_SQL.NUMBER_TABLE
);



FUNCTION GET_JOB_TITLE ( P_ALT_TITLE VARCHAR2 ) RETURN VARCHAR2;

end;
/
show errors

CREATE OR REPLACE PACKAGE BODY RDM.SQA_QC
IS

FUNCTION GET_JOB_TITLE ( P_ALT_TITLE VARCHAR2 ) RETURN VARCHAR2
IS

JOB_TITLE   VARCHAR2(100 BYTE);
SQL_STMT    VARCHAR2(100 BYTE);
CNT         NUMBER;
GC          GenRefCursor;
JT          JOB_TITLES;

BEGIN


SQL_STMT := 'SELECT JOB_TITLE, JOB_NAMES, ACTIVE FROM SQA_QC_JOB_TITLES WHERE ACTIVE = 1 AND  JOB_NAME = :A';

OPEN GC FOR SQL_STMT USING P_ALT_TITLE;

FETCH GC BULK COLLECT INTO JT.JOB_TITLE,
                           JT.JOB_NAMES,
                           JT.ACTIVE;

CNT := JT.JOB_TITLE.COUNT;

IF ( CNT = 0 )
   THEN
       JOB_TITLE := 'Job Title Unknown';
else
       JOB_TITLE := JT.JOB_TITLE(1);

END IF;

CLOSE GC;


RETURN JOB_TITLE;

END;


end;
/
show errors;


